CREATE TABLE products (
    ID 			    INT	NOT NULL AUTO_INCREMENT,
	NAME 		    VARCHAR(50)	NOT NULL,
	DESCRIPTION     VARCHAR(200) NOT NULL,
    PRICE            FLOAT NOT NULL,
    IMAGE_PATH       VARCHAR(200) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE INDEX IDX_PRODUCTS_ID ON products (ID);

